version: '3'
services:
  python3:
    build: ./deploy/proxy_pool
    container_name: proxy_pool
    restart: unless-stopped
    volumes:
      - .:/app
      - /var/data/proxy_pool_cache:/app/cache
    ports:
      - 8010:8010
      - 5000:5000
  redis:
    image: redis:6.2.6
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - /var/data/redis:/data
      - /var/log/redis:/logs
      - ./deploy/redis/conf/redis.conf:/etc/redis/redis.conf
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: phpredisadmin
    restart: unless-stopped
    environment:
      - REDIS_1_HOST=107.150.102.81
      - REDIS_1_NAME=docker_redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=123456
      - REDIS_1_DATABASES=0
    ports:
      - 8011:80
